### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by TheMasterDuper** [BlockHorizons/BlockQuests#3]
Hello, when I install the plugin, this is what I get in my console: [07:34:34] [Server thread/CRITICAL]: Error: "Class 'SQLite3' not found" (EXCEPTION) in "BlockQuests-master/src/BlockHorizons/BlockQuests/database/SQLiteQuestDatabase" at line 26
Then the plugin disables instantly.

Please help me/fix this error.

**Comment by Sandertv** [comment]
Please enable the SQLite PHP extension.

**Comment by TheMasterDuper** [comment]
Thank you for letting me know. I'm new to this stuff, sorry!
